import { chromium } from 'playwright';
const EXE = '/home/jimmyfoh/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome';
const browser = await chromium.launch({ executablePath: EXE, args: ['--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
await page.goto('http://localhost:5199/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
await page.click('#btn-start');
await page.waitForTimeout(1600);
await page.keyboard.down('KeyW');
await page.waitForTimeout(900);
await page.keyboard.up('KeyW');
const s1 = await page.evaluate(() => ({ pos: [...window.__JJ.game.pos.toArray()], grounded: window.__JJ.game.onGround, falls: window.__JJ.game.falls }));
console.log('after W:', JSON.stringify(s1));
await page.screenshot({ path: '/tmp/jj-shots/dbg1.png' });
const s2 = await page.evaluate(() => ({ pos: [...window.__JJ.game.pos.toArray()], grounded: window.__JJ.game.onGround, falls: window.__JJ.game.falls }));
console.log('after shot:', JSON.stringify(s2));
await page.keyboard.press('Space');
await page.waitForTimeout(150);
const s3 = await page.evaluate(() => ({ pos: [...window.__JJ.game.pos.toArray()], grounded: window.__JJ.game.onGround, jumps: window.__JJ.game.jumpsLeft }));
console.log('after space:', JSON.stringify(s3));
await browser.close();
